---
title: "Homework_05_Khum_again"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

## Laoding libraries for whole data analysis

```{r}
# Loading libraries need for analysis
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(maps)
library(sf)
library(tigris)
library(forcats)
library(stringr)
library(broom)
library(readxl)
library(lubridate)
library(tidytext)
library(tigris)

```

### Creating new direcotory data and writing

```{r}
#dir.create("data")
#dir.create("writing")
```

## Loading and refining homicide data sets

```{r}
# Loading homicide data sets
homicide <- read_csv("../data/homicide_data.csv")
```

## tracts, block groups, county subdivisions
## use sf_box to limit the extent of plots
```{r}
city<- homicide %>%
  filter(state == "CO")

co_counties <- counties(state = "CO", cb = TRUE, class = "sf")

# getting tracts for colorado
tracts_co<- tracts(state = "CO", cb = TRUE, class = "sf")
# getting block grous for colorado
block_groups_co<- block_groups(state = "CO", cb = TRUE, class = "sf")
# getting county subdivisions
county_sub_co<- county_subdivisions(state = "CO", cb = TRUE, class = "sf")

# making sf objects for denver homicides
co_homi<- st_as_sf(city, coords=c("lon", "lat")) %>%
  st_set_crs(4269) %>%
  mutate(unsolved = factor(disposition != "Closed by arrest")) %>%
  mutate(unsolved = fct_recode(unsolved,
                               Unsolved = "TRUE",
                               Solved = "FALSE")) %>%
  mutate(victim_race = fct_lump(victim_race,n=3))

## plots for homicide
den_homi<- ggplot()+
   geom_sf(data = co_counties)+
    geom_sf(data = county_sub_co)+
    geom_sf(data = block_groups_co)+
  geom_sf(data = tracts_co, color = "blue", fill = "white", alpha = 0.2)+
  geom_sf(data = co_homi, aes(color = victim_race,
                              fill = victim_race))+
  labs(color = "Victim Race", fill = "Victim Race") + 
  #xlim(c(-105.06,-104.75))+
  #ylim(c(39.63,39.8))+
  coord_sf(xlim = c(-105.06029,-104.74151), ylim = c(39.63327,39.79747), expand = FALSE)+
  facet_wrap(~unsolved, ncol=2)+
  scale_x_continuous(breaks=c(-104.8, -104.9, -105))+
  scale_y_continuous(breaks=c(39.64,39.71,39.78))
den_homi

```

## Saving the output as png file

```{r}
# Saving the figure

ggsave("../figure/den_homi.png", width = 20, height = 3, dpi = 300, units = c("in"))

```

```{r}
# getting data for baltimore city and refining data with lubridate packages
# changed reported_date into ymd pattern
# seperated year, month and day into varibles
# converted month into summer(May-October) and winter (November-April)
city_bal<- homicide %>%
  filter(city == "Baltimore") %>%
  mutate(reported_date = ymd(reported_date)) %>%
  mutate_at(vars(reported_date), funs(year,month,day)) %>%
  mutate(month_type = ifelse(month >= 5 & month <= 10, "Summer", "Winter")) %>%
  mutate(month = factor(month))

```

## Homocide graph plots

```{r}
# lets summarize the homicides in baltimore according to month
homi_month<- city_bal %>%
  group_by(month,month_type, year) %>%
  count()
homi_month

balti_homi <-ggplot(data = homi_month)+
  geom_bar(aes(x = year, y = n, , group = month,fill = month_type), stat = "identity", position = "dodge")+
  geom_smooth(aes(x = year, y = n),se=FALSE)+
  scale_fill_manual(values=c("gray", "skyblue"))+
  theme(legend.position= "bottom",
        legend.title=element_blank())+
  ggtitle("Homicides in Baltimore, MD")+
  labs(x ="Date", y="Monthly homicides")+
  geom_vline(xintercept=2014.8, linetype="dashed", color = "red", size = 1.5)+
  annotate("text", x = 2013.9, y = 40, label = " Arrest of\n Freddie Gray")
balti_homi

```

```{r}
# Saving the figure
ggsave("../figure/balti_homi.png", width = 15, height = 5, dpi = 300, units = c("in"))
```

